### ISSUE TITLE
Would it be possible to mark `Event.eventTime` as `Date?`?

### ISSUE THREAD

**Issue by guppy0130** [swiftkube/model#11]
Okay, I admit I'm asking for this feature here because upstream kubernetes has yet to merge https://github.com/kubernetes/kubernetes/pull/100600 and/or resolve https://github.com/kubernetes/kubernetes/issues/82665, so please feel free to close this if you want to follow only spec (would totally understand that!).

In an `Event`, the `eventTime` is required/not allowed to be `nil`:

https://github.com/swiftkube/model/blob/2d10b91ee6fa3584807ec859370b62512760c4ec/Sources/Model/events/v1/Event%2Bevents.v1.swift#L74

Which correctly [follows the spec provided by upstream](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/#Event).

That being said, because kubelets aren't yet using the Events v1 API, `eventTime` is sometimes `nil` in the response from the cluster:

```json
{
  "kind": "EventList",
  "apiVersion": "events.k8s.io/v1",
  "metadata": { "resourceVersion": "10891762" },
  "items": [
    {
      "metadata": { ... },
      "eventTime": null,
      "reason": "FreeDiskSpaceFailed",
      "regarding": {
        "kind": "Node",
        "name": "k3s-node-1",
        "uid": "k3s-node-1"
      },
      "note": "(combined from similar events): Failed to garbage collect required amount of images. Attempted to free 462039449 bytes, but only found 0 bytes eligible to free.",
      "type": "Warning",
      "deprecatedSource": { "component": "kubelet", "host": "k3s-node-1" },
      "deprecatedFirstTimestamp": "2024-01-27T06:54:50Z",
      "deprecatedLastTimestamp": "2024-02-10T19:15:03Z",
      "deprecatedCount": 3679
    }
  ]
}
```

I've truncated `.items[0].metadata` because it wasn't relevant.

Would it be possible to type `Event.eventTime` as `Date?`, allowing the `JSONDecoder` to decode these events as well?

I discovered this when I couldn't get any events from the kubelet/node:

```
(lldb) p try jsonDecoder.decode(SwiftkubeModel.events.v1.EventList.self, from: data)
(DecodingError) <invalid> (0x80)
```

where `data` is `NSData` containing the full reply from the server.

I compared the server response against the struct types and found that discrepancy. Tested isolating it to just that struct member/type and got the same error:

```
(lldb) p try jsonDecoder.decode(Date.self, from: Data(base64Encoded: "bnVsbA==")!)
(DecodingError) <invalid> (0x80)
```

edit: FWIW, I found https://github.com/swiftkube/model/blob/2d10b91ee6fa3584807ec859370b62512760c4ec/Sources/Model/core/v1/Event%2Bcore.v1.swift#L62 which has different keys, so I don't think this is the right struct to use?

**Comment by guppy0130** [comment]
Sorry, nevermind, user error - I realized there's also the `core.v1.Event` accessed via `client.events` instead of `client.eventsV1.events`, which would be sufficient until upstream migrates everything to their Events V1

**Comment by iabudiab** [comment]
Hey there, sorry for not replying sooner. I was a little bit under the weather the last week.

Glad it worked out with `core.v1.Event` 😸
