### ISSUE TITLE
Kubernetes Release Schedule

### ISSUE THREAD

**Issue by ewilken** [swiftkube/model#8]
Thanks a lot for this great set of libraries!

I've been wondering what Swiftkube's schedule for supporting newer Kubernetes releases than 1.24 is and whether there's something blocking it feature-wise or whether it's just a matter of running modelgen on a newer Kubernetes version.

If you can use any help on keeping the model up to date, I'd love to help!

**Comment by iabudiab** [comment]
@ewilken Hey there 👋 very sorry for the late reply.

I'm really glad you like the project. And you're more than welcome to contribute! Any help is much appreciated 🙇 

There is no set schedule and there is nothing blocking it except for the amount of free time I get. Updating the model is, as you said, just a matter of running `modelgel` on a new version and then moving files around.

If you want and have the time, you could maybe automate the process of keeping `model` up-to-date. This is one the many things on my todo list, however, pretty low in terms of priority 😅

**Comment by iabudiab** [comment]
I'll try to squeeze some time in the next couple of days to update the model.

**Comment by ewilken** [comment]
No worries at all! Feel you! 😄 Thanks a lot for the work you're doing here! 🙂

Please don't feel pressured to rush this out or something. I'm about to send you another PR tweaking the response size limit on GETting logs. I might have a closer look at `modelgen` then afterwards, if I find the time for it before you do.

Closing, as my question was answered. 🙂
